
// This file has been generated by the GUI designer. Do not modify.
namespace CCategoria.Properties
{
	public partial class ActionGroup
	{
		public virtual void Build()
		{
			// Action group CCategoria.Properties.ActionGroup
		}
	}
}
