
// This file has been generated by the GUI designer. Do not modify.
namespace CCategoria
{
	public partial class DbComandHelper
	{
		public virtual void Build()
		{
			// Action group CCategoria.DbComandHelper
		}
	}
}
